### ISSUE TITLE
find with :type => :fulltext raising a NativeException

### ISSUE THREAD

**Issue by markburns** [andreasronge/neo4j-wrapper#5]
I'm getting the following problem against the latest version

``` ruby
Tanaka.find english: "Why*", type: :fulltext
```
# Stacktrace

```
org.neo4j.cypher.SyntaxException: Unknown identifier `fulltext`
org/neo4j/cypher/internal/executionplan/ExecutionPlanImpl.scala:129:in `produceAndThrowException'
org/neo4j/cypher/internal/executionplan/ExecutionPlanImpl.scala:56:in `prepareExecutionPlan'
org/neo4j/cypher/internal/executionplan/ExecutionPlanImpl.scala:32:in `'
org/neo4j/cypher/ExecutionEngine.scala:61:in `apply'
org/neo4j/cypher/ExecutionEngine.scala:61:in `apply'
org/neo4j/cypher/internal/LRUCache.scala:31:in `getOrElseUpdate'
org/neo4j/cypher/ExecutionEngine.scala:61:in `prepare'
org/neo4j/cypher/ExecutionEngine.scala:55:in `execute'
org/neo4j/cypher/ExecutionEngine.scala:52:in `execute'
org/neo4j/cypher/javacompat/ExecutionEngine.java:63:in `execute'
/Users/markburns/.rvm/gems/jruby-1.6.7.2/gems/neo4j-core-2.2.0.rc1-java/lib/neo4j/neo4j.rb:127:in `_query'
/Users/markburns/.rvm/gems/jruby-1.6.7.2/gems/neo4j-core-2.2.0.rc1-java/lib/neo4j-core/traversal/traverser.rb:37:in `each'
```
# evaluation of code at:

`/Users/markburns/.rvm/gems/jruby-1.6.7.2/gems/neo4j-core-2.2.0.rc1-java/lib/neo4j/neo4j.rb:127`

``` ruby
    124     def _query(q)
   125        engine = Java::OrgNeo4jCypherJavacompat::ExecutionEngine.new(db)
   126        debugger
=> 127        result = engine.execute(q)
   128        Neo4j::Cypher::ResultWrapper.new(result)
   129      end

eval q
"START v2=node(2) MATCH (v2)-[:`_all`]->(v1) WHERE v1.english = \"Why*\" and v1.type = fulltext RETURN v1"

```

**Comment by markburns** [comment]
Obviously fulltext is being passed through to cypher and presumably it's an API change?
What's the new API or is there a workaround?

**Comment by markburns** [comment]
OK seems like it needs two hashes or a string first argument. So

``` ruby
Tanaka.find("english: Why*", {type: :fulltext})
```

**Comment by andreasronge** [comment]
Hmm, thanks. Looks like you are using neo4j and not only the neo4j-wrapper gem, which has a little different syntax.
The docs has been moved to https://github.com/andreasronge/neo4j/wiki.

Btw, as you saw in the stacktrace, if you don't declare an index it will use cypher query instead (like a SQL full table scan but done with fast java code instead). This is a new feature
